services:
  postgres:
    image: postgres:15
    container_name: delivery_postgres
    restart: always
    environment:
      POSTGRES_USER: robot_delivery_user
      POSTGRES_PASSWORD: deliverypassword
      POSTGRES_DB: robot_delivery_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: